baseURL = "http://example.org/"
languageCode = "en-us"
title = "Mermaid Examples"

# Change the default theme to be use when building the site with Hugo
theme = "learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]